# Generated by Django 6.0.3 on 2026-04-11 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication_hub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailaccount',
            name='is_etl_enabled',
            field=models.BooleanField(default=False, help_text='Enable automated Resume Extraction for this account'),
        ),
    ]
