# Generated by Django 6.0.3 on 2026-04-12 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication_hub', '0002_mailaccount_is_etl_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailaccount',
            name='sync_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('syncing', 'Syncing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
