# Generated by Django 6.0.3 on 2026-04-12 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication_hub', '0003_mailaccount_sync_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailattachment',
            name='file_name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='mailmessage',
            name='recipient',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='mailmessage',
            name='sender',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='mailmessage',
            name='subject',
            field=models.TextField(blank=True),
        ),
    ]
