# Generated by Django 6.0.3 on 2026-03-30 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_working_date',
            field=models.DateField(blank=True, help_text='Required when status is EXITED', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('EXITED', 'Exited'), ('BLACKLIST', 'Blacklist')], default='ACTIVE', max_length=20),
        ),
    ]
