# Generated by Django 6.0.3 on 2026-03-30 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_employeeprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeeprofile',
            old_name='location',
            new_name='street',
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='zip_code',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
