# Generated by Django 6.0.3 on 2026-03-30 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_location_employeeprofile_street_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
