# Generated by Django 6.0.3 on 2026-03-30 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_employeeprofile_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
    ]
