# Generated by Django 6.0.3 on 2026-04-14 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Target Role Name', max_length=255)),
                ('job_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('headcount', models.PositiveIntegerField(default=1, help_text='No. of Openings')),
                ('location_mode', models.CharField(choices=[('ON_SITE', 'On-Site'), ('HYBRID', 'Hybrid'), ('REMOTE', 'Remote')], default='ON_SITE', max_length=20)),
                ('location', models.CharField(help_text='Hiring Location (e.g. New York, USA)', max_length=255)),
                ('min_experience', models.PositiveIntegerField(help_text='Min Experience in years')),
                ('max_experience', models.PositiveIntegerField(help_text='Max Experience in years')),
                ('min_salary', models.DecimalField(decimal_places=2, help_text='Min Salary (LPA)', max_digits=10)),
                ('max_salary', models.DecimalField(decimal_places=2, help_text='Max Salary (LPA)', max_digits=10)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('DRAFT', 'Draft'), ('CLOSED', 'Closed')], default='DRAFT', max_length=20)),
                ('job_description', models.TextField(blank=True)),
                ('requirements', models.TextField(blank=True, help_text='Special requirements or skills')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_positions', to='organizations.department')),
            ],
            options={
                'verbose_name': 'Job Position',
                'verbose_name_plural': 'Job Positions',
                'ordering': ['-created_at'],
            },
        ),
    ]
