# Generated by Django 6.0.3 on 2026-04-14 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_etl', '0002_ingestionlog_message'),
        ('recruitment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('SHORTLIST', 'Shortlist'), ('TELEPHONIC', 'Telephonic'), ('SCREENING', 'Screening'), ('TECHNICAL', 'Technical'), ('MANAGER', 'Manager'), ('HIRED', 'Hired'), ('REJECTED', 'Rejected')], default='SHORTLIST', max_length=50)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected')], default='IN_PROGRESS', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='candidate_etl.candidateprofile')),
                ('job_position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='recruitment.jobposition')),
            ],
            options={
                'verbose_name': 'Job Application',
                'verbose_name_plural': 'Job Applications',
                'unique_together': {('job_position', 'candidate')},
            },
        ),
    ]
