# Generated by Django 6.0.3 on 2026-04-14 17:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_etl', '0002_ingestionlog_message'),
        ('recruitment', '0002_jobapplication'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobapplication',
            options={'ordering': ['-updated_at']},
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='applied_at',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='stage',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='status',
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='current_stage',
            field=models.CharField(choices=[('SHORTLIST', 'Shortlist'), ('TELEPHONIC', 'Telephonic Round'), ('SCREENING', 'Screening'), ('TECHNICAL', 'Technical Interview'), ('MANAGER', 'Managerial Round'), ('HIRED', 'Hired'), ('REJECTED', 'Rejected')], default='SHORTLIST', max_length=50),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_applications', to='candidate_etl.candidateprofile'),
        ),
    ]
