# Generated by Django 6.0.3 on 2026-04-12 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_etl', '0001_initial'),
        ('communication_hub', '0003_mailaccount_sync_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingestionlog',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etl_logs', to='communication_hub.mailmessage'),
        ),
    ]
